name: multifirebaseauthentication
description: Multi Firebase Authentication

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.5.9
  provider: ^6.0.1
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true